apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200-399"
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.groupName | quote }}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "sentiment-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
