apiVersion: v1
kind: Service
metadata:
  name: sentiment-api
spec:
  selector:
    app: sentiment-api
  ports:
    - protocol: TCP
      port: 80         # പുറത്ത് നിന്നുള്ള വിളി (External Port)
      targetPort: 8000 # ആപ്പ് ഉള്ളിലെ ശരിക്കുള്ള പോർട്ട് (App Port)
  type: ClusterIP
